Bundlesize added
eyedea-io/webmaster-kit pull request #16
Opened 2018-10-10 20:47 UTC by sasalx

For #14 .

2018-10-13 11:50 UTC, Idered requested changes

2018-10-13 11:50 UTC, Idered commented on package.json
> +	"private": true,
Please use project spacing size(2 spaces) - install editorconfig in your code editor

2018-10-13 20:07 UTC, sasalx commented
Edited accordingly.

2018-10-15 21:13 UTC, Idered approved these changes

2018-10-15 21:13 UTC, merged